### ISSUE TITLE
Put all unrecognized properties under "custom"

### ISSUE THREAD

**Issue by andrewcurioso** [andrewcurioso/raml-serverless#8]
If a RAML property cannot be understood it should be put under custom so that if a RAML file is generated from the `serverless.yml` file later, it will have the same properties.

Example:
```yaml
custom:
  documentation:
    raml:
      title: My Awesome API
```
